//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Booking
    {
        public int BookingId { get; set; }
        [Required(ErrorMessage = "Description is required.")]
        public string Description { get; set; }
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Date is required.")]
        public System.DateTime BookingDate { get; set; }
        public string AspNetUsersId { get; set; }
        public string DoctorName { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
